version: '3'

networks:
  nw:
    driver: bridge
  nw2:
    driver: bridge

services:

  pinpong:
    container_name: peng
    build: ./peng
    command: python3 manage.py runserver 0.0.0.0:8081
    volumes:
      - ./peng:/app
    ports:
      - "8081:8081"
    networks:
      - nw2

  nginx:
    build: ./frontend
    container_name: gamefronty
    ports:
      - "8082:8082"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html/
    networks:
      - nw
